services:
  auth-service:
    build:
      context: ./microservices
      dockerfile: auth-service/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./microservices/auth-service/.env
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - app-network

  recipe-service:
    build:
      context: ./microservices
      dockerfile: recipe-service/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./microservices/recipe-service/.env
    depends_on:
      - recipe-db
      - rabbitmq
    networks:
      - app-network

  social-service:
    build:
      context: ./microservices
      dockerfile: social-service/Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./microservices/social-service/.env
    depends_on:
      - social-db
      - rabbitmq
    networks:
      - app-network

  auth-db:
    image: postgres:14
    env_file:
      - ./microservices/auth-service/.env
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  recipe-db:
    image: postgres:14
    env_file:
      - ./microservices/recipe-service/.env
    ports:
      - "5434:5432"
    volumes:
      - recipe-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  social-db:
    image: postgres:14
    env_file:
      - ./microservices/social-service/.env
    ports:
      - "5435:5432"
    volumes:
      - social-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  auth-db-data:
  recipe-db-data:
  social-db-data: